### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by 239573049** [liwuqingxin/avalonia.devtools.issues#3]
功能建议
- [x]  提供参数是否默认启动就开启DevTools
- [x] 建议将鼠标悬停定位组件放置最左边
![fb15b1fa650e5b267fd233e9030f046](https://github.com/user-attachments/assets/20fbb68c-cbdc-4356-8cad-29ba87070a80)

**Comment by liwuqingxin** [comment]
@239573049 Please send an email to [toolspeed@163.com](mailto:toolspeed@163.com) to tell us your toolspeed account. We will extend your plan for three months.

**Comment by liwuqingxin** [comment]
* New Configuration：Open the devtools immediately the application is running next time.

![image](https://github.com/user-attachments/assets/c2baf0d8-85be-427c-916b-410a1f195383)
